using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Solutions.Problems
{
    //389. Find the Difference
    //You are given two strings s and t.

    //String t is generated by random shuffling string s and then add one more letter at a random position.


    //Return the letter that was added to t.
    internal class _389_
    {
        public char FindTheDifference(string s, string t)
        {
            //Dictionary<char, int> sCountLetters = new();
            //Dictionary<char, int> tCountLetters = new();
            //foreach (char c in s)
            //{
            //    if (sCountLetters.ContainsKey(c))
            //    {
            //        sCountLetters[c]++;
            //    }
            //    else
            //    {
            //        tCountLetters[c] = 1;
            //    }
            //}
            //foreach (char c in t)
            //{
            //    if (tCountLetters.ContainsKey(c))
            //    {
            //        tCountLetters[c]++;
            //    }
            //    else
            //    {
            //        tCountLetters[c] = 1;
            //    }
            //}
            //foreach(char c in tCountLetters.Keys) {
            //    if (!sCountLetters.ContainsKey(c)) return c;
            //    if(sCountLetters[c] != tCountLetters[c]) return c;
            //}

            //return 'a';
            char result = (char)0;
            foreach (char c in s + t)
            {
                result ^= c;
            }
            return result;
        }
    }
}
